apiVersion: v1
kind: Service
metadata:
  name: graf-service
  labels:
    app: graf
spec:
  ports:
    - port: 3000
      name: graf
      nodePort: 30000
  type: NodePort
  selector:
    app: graf

    