apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: graf-pvc
  labels:
    name: grfpvc

spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
                 



