apiVersion: v1
kind: Service
metadata:
  name: prom-service
  labels:
    app: prom
spec:
  ports:
    - port: 9090
      name: prom
      nodePort: 31000
  type: NodePort
  selector:
    app: prom

    